local web = { "prettier" }

return {
    lsp = {
        nix = { "nixd" },
        lua = { "lua_ls" },
        rust = { "rust_analyzer" },
        python = { "pyright", "ruff" },
        go = { "gopls" },
        java = { "jdtls" },
        c = { "clangd" },
        cpp = { "clangd" },
        javascript = { "ts_ls" },
        javascriptreact = { "ts_ls" },
        typescript = { "ts_ls" },
        typescriptreact = { "ts_ls" },
        json = { "jsonls" },
        jsonc = { "jsonls" },
        html = { "html" },
        css = { "cssls" },
        scss = { "cssls" },
        yaml = { "yamlls" },
        markdown = { "marksman" },
        toml = { "taplo" },
        sh = { "bashls" },
        bash = { "bashls" },
        ruby = { "ruby_lsp" },
        zig = { "zls" },
    },

    formatters = {
        nix = { "nixfmt" },
        lua = { "stylua" },
        rust = { "rustfmt" },
        python = { "ruff_format" },
        go = { "gofmt" },
        c = { "clang-format" },
        cpp = { "clang-format" },
        javascript = web,
        javascriptreact = web,
        typescript = web,
        typescriptreact = web,
        json = web,
        jsonc = web,
        html = web,
        css = web,
        scss = web,
        yaml = web,
        markdown = web,
        toml = { "taplo" },
        sh = { "shfmt" },
        bash = { "shfmt" },
        fish = { "fish_indent" },
        java = { "google-java-format" },
        ruby = { "rubocop" },
        zig = { "zigfmt" },
    },

    commands = {
        ts_ls = { "typescript-language-server", "--stdio" },
        jsonls = { "vscode-json-language-server", "--stdio" },
        html = { "vscode-html-language-server", "--stdio" },
        cssls = { "vscode-css-language-server", "--stdio" },
        yamlls = { "yaml-language-server", "--stdio" },
        jdtls = { "jdtls" },
        ruby_lsp = { "ruby-lsp" },
    },

    dependencies = {
        jdtls = { "java" },
        ["rust-analyzer"] = { "cargo", "rustc" },
        gopls = { "go" },
        ["ruby-lsp"] = { "ruby" },
    },

    packages = {
        nixd = "nixd",
        nixfmt = "nixfmt",
        ["lua-language-server"] = "lua-language-server",
        stylua = "stylua",
        ["rust-analyzer"] = "rust-analyzer",
        rustfmt = "rustfmt",
        cargo = "cargo",
        rustc = "rustc",
        ["pyright-langserver"] = "pyright",
        ruff = "ruff",
        gopls = "gopls",
        gofmt = "go",
        go = "go",
        clangd = "clang-tools",
        ["clang-format"] = "clang-tools",
        ["typescript-language-server"] = "typescript-language-server",
        prettier = "prettier",
        ["vscode-json-language-server"] = "vscode-langservers-extracted",
        ["vscode-html-language-server"] = "vscode-langservers-extracted",
        ["vscode-css-language-server"] = "vscode-langservers-extracted",
        ["yaml-language-server"] = "yaml-language-server",
        marksman = "marksman",
        taplo = "taplo",
        ["bash-language-server"] = "bash-language-server",
        shfmt = "shfmt",
        fish_indent = "fish",
        ["google-java-format"] = "google-java-format",
        jdtls = "jdt-language-server",
        java = "jdk",
        ["ruby-lsp"] = "ruby-lsp",
        ruby = "ruby",
        rubocop = "rubocop",
        zig = "zig",
        zls = "zls",
    },
}
